# admin login
POST http://localhost:5000/auth
Content-Type: application/json

{
    "password": "sample"
}

###
# Get all articles
GET http://localhost:5000/articles?page=1

###
# Get one article
GET http://localhost:5000/articles/61272344f46077dc239bf8dd


###
# Post an article
POST http://localhost:5000/articles
Content-Type: application/json

{
    "password":"84a4eeee15b296c32af4dee0bb2046fcba4da394d8e172df6441888b3353dd947f70cd34c54c412658884d9e63670783bd45b57cccd8df03feb3356fd26f0a3b",
    "article": {
        "title": "Sample Title 69",
        "description": "Sample Desc 3",
        "wallpaper": "nil",
        "markdown": "# This is title3 ## This is subtitle 2134"
    }
}

###
# Edit an article
PUT http://localhost:5000/articles/6127229df46077dc239bf8d8
Content-Type: application/json

{
    "password":"71057ba536e65b6d115059db1d0eef34bce0f21264329437ed034e4984e6be7da42891d773c7f8347e6a47dce8d9faf2204da82d687f3f43675341273155cbbf",
    "article": {
        "title": "Edited Title",
        "description": "Edited Desc 2",
        "wallpaper": "nil",
        "markdown": "# This is edited title ## This is edited subtitle"
    }
}

### Delete an Article
DELETE http://localhost:5000/articles/6127229df46077dc239bf8d8
Content-Type: application/json

{
    "password":"71057ba536e65b6d115059db1d0eef34bce0f21264329437ed034e4984e6be7da42891d773c7f8347e6a47dce8d9faf2204da82d687f3f43675341273155cbbf"
}

###
# Post a comment
POST http://localhost:5000/articles/comment/613251a1915fb738a5ba16f3
Content-Type: application/json

{
    "comment": "Sample Comment",
    "password": "32077724d55fc17e305daf3d4e0eb947ddf2a2c12ed65f546c393d92d736a8cc4d7904e601c60bfecf7dfa1eb7057cc6ef145b7d94418eea8db7bf67fafa89ff"
}



# User routes

###
# Register
POST http://localhost:5000/user/register
Content-Type: application/json

{
    "username": "Test User",
    "email": "example@gmail.com",
    "password": "test-password"
}

###
# Login
POST http://localhost:5000/user/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "test-password"
}

###
# Update about
POST http://localhost:5000/user/update-desc
Content-Type: application/json

{
    "password": "32077724d55fc17e305daf3d4e0eb947ddf2a2c12ed65f546c393d92d736a8cc4d7904e601c60bfecf7dfa1eb7057cc6ef145b7d94418eea8db7bf67fafa89ff",
    "desc": "Updated profile desc"
}

# Consultant
###
POST http://localhost:5000/consultant/register
Content-Type: application/json

{
    "username": "Test Consultant",
    "email": "example@gmail.com",
    "password": "test-password"
}

###
# Login
POST http://localhost:5000/consultant/login
Content-Type: application/json

{
    "email": "example@gmail.com",
    "password": "test-password"
}